### ISSUE TITLE
OSError: got end of file during message

### ISSUE THREAD

**Issue by ZhuFengdaaa** [facebookresearch/habitat-sim#1030]
## ❓ Questions and Help
I use a device with 251GB CPU memory but it fails with `OSError: got end of file during message`. The memory is full when it fails. I use python 3.6.10, pytorch v1.4.0 and CUDA V9.2. My habitat-sim version is `ae6ba1cdc772f7a5dedd31cbf9a5b77f6de3ff0f` and habitat-lab version is `676e593b953e2f0530f307bc17b6de66cff2e867`. I doubt if the 3D assets are not deallocated even though the log has printed like this: 
```
2021-01-17 19:43:31,452 update: 395     fps: 24.775                                                                                                                                                [59/1550]
2021-01-17 19:43:31,453 update: 395     env-time: 29744.865s    pth-time: 2980.210s     frames: 811008
2021-01-17 19:43:31,453 Average window size: 50  reward: 1.082  distance_to_currgoal: 7.610  distance_to_multi_goal: 23.422  sub_success: 0.000  success: 0.000  episode_length: 42.650  mspl: 0.000  percen
tage_success: 0.030  ratio: 1.181  pspl: 0.029
2021-01-17 19:43:46,685 update: 396     fps: 24.826
2021-01-17 19:43:46,686 update: 396     env-time: 29757.911s    pth-time: 2982.354s     frames: 813056
2021-01-17 19:43:46,686 Average window size: 50  reward: 1.088  distance_to_currgoal: 7.611  distance_to_multi_goal: 23.417  sub_success: 0.000  success: 0.000  episode_length: 42.726  mspl: 0.000  percen
tage_success: 0.031  ratio: 1.180  pspl: 0.029
2021-01-17 19:44:02,698 update: 397     fps: 24.876
2021-01-17 19:44:02,699 update: 397     env-time: 29771.738s    pth-time: 2984.517s     frames: 815104
2021-01-17 19:44:02,699 Average window size: 50  reward: 1.075  distance_to_currgoal: 7.615  distance_to_multi_goal: 23.467  sub_success: 0.000  success: 0.000  episode_length: 42.499  mspl: 0.000  percen
tage_success: 0.031  ratio: 1.180  pspl: 0.029
I0117 19:44:03.557344 17883 Simulator.cpp:38] Deconstructing Simulator
I0117 19:44:03.557802 17883 PhysicsManager.cpp:30] Deconstructing PhysicsManager
I0117 19:44:03.557828 17883 SemanticScene.h:40] Deconstructing SemanticScene
I0117 19:44:03.564234 17883 SceneManager.h:24] Deconstructing SceneManager
I0117 19:44:03.564270 17883 SceneGraph.h:25] Deconstructing SceneGraph
I0117 19:44:03.565155 17883 RenderTarget.h:51] Deconstructing RenderTarget
I0117 19:44:03.566596 17883 Sensor.h:80] Deconstructing Sensor
I0117 19:44:03.566629 17883 RenderTarget.h:51] Deconstructing RenderTarget
I0117 19:44:03.567698 17883 Sensor.h:80] Deconstructing Sensor
I0117 19:44:03.567772 17883 SceneGraph.h:25] Deconstructing SceneGraph
I0117 19:44:03.611171 17883 Renderer.cpp:33] Deconstructing Renderer
I0117 19:44:03.611207 17883 WindowlessContext.h:16] Deconstructing WindowlessContext
I0117 19:44:03.611235 17883 WindowlessContext.cpp:245] Deconstructing GL context
I0117 19:44:03.650717 17883 Simulator.cpp:64] Loading navmesh from data/scene_datasets/mp3d/PX4nDJXEHrG/PX4nDJXEHrG.navmesh
I0117 19:44:03.653225 17883 Simulator.cpp:66] Loaded.
I0117 19:44:03.653308 17883 SceneGraph.h:92] Created DrawableGroup: 
I0117 19:44:03.659265 17883 WindowlessContext.cpp:100] [EGL] Detected 8 EGL devices
I0117 19:44:03.677284 17883 WindowlessContext.cpp:121] [EGL] Selected EGL device 0 for CUDA device 0
I0117 19:44:03.703464 17883 WindowlessContext.cpp:135] [EGL] Version: 1.5
I0117 19:44:03.703526 17883 WindowlessContext.cpp:136] [EGL] Vendor: NVIDIA
Renderer: TITAN V/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 430.64
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I0117 19:44:04.106724 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
W0117 21:08:09.739675 17883 ResourceManager.cpp:210] :
---
Physics was enabled and Bullet physics engine was specified, but the project is built without Bullet support. Objects added to the scene will be restricted to kinematic updates only. Reinstall with --bull
et to enable Bullet dynamics.
---

---
I0117 21:08:09.762893 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_red.phys_properties.json
I0117 21:08:09.809247 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.889254 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_green.phys_properties.json
I0117 21:08:09.890094 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.890965 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_blue.phys_properties.json
I0117 21:08:09.891743 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.892717 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_yellow.phys_properties.json
I0117 21:08:09.893366 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.894170 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_white.phys_properties.json
I0117 21:08:09.894793 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.895591 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_pink.phys_properties.json
I0117 21:08:09.896272 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.897284 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_black.phys_properties.json
I0117 21:08:09.897907 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.898725 17883 ResourceManager.cpp:228] loading object: ./data/objects/cylinder_cyan.phys_properties.json
I0117 21:08:09.899365 17883 ResourceManager.cpp:1105] Importing Basis files as BC7
I0117 21:08:09.900156 17883 ResourceManager.cpp:231] loaded object templates: 8
I0117 21:08:09.903051 17883 Simulator.cpp:132] Loading house from data/scene_datasets/mp3d/PX4nDJXEHrG/PX4nDJXEHrG.house
I0117 21:08:09.903144 17883 Simulator.cpp:138] Loading semantic mesh data/scene_datasets/mp3d/PX4nDJXEHrG/PX4nDJXEHrG_semantic.ply
I0117 21:08:09.904471 17883 SceneGraph.h:92] Created DrawableGroup: 
I0117 21:08:36.464275 17883 Simulator.cpp:151] Loaded.
I0117 21:08:36.899024 17883 simulator.py:145] Loaded navmesh data/scene_datasets/mp3d/PX4nDJXEHrG/PX4nDJXEHrG.navmesh
2021-01-17:21:08:36,899 INFO     [simulator.py:145] I0117 21:08:36.899024 17883 simulator.py:145] Loaded navmesh data/scene_datasets/mp3d/PX4nDJXEHrG/PX4nDJXEHrG.navmesh
Traceback (most recent call last):
  File "habitat_baselines/run.py", line 65, in <module>
    main()
  File "habitat_baselines/run.py", line 18, in main
    run_exp(**vars(args))
  File "habitat_baselines/run.py", line 60, in run_exp
    trainer.train()
  File "/multiON/habitat_baselines/rl/ppo/ppo_trainer.py", line 1220, in train
    rollouts, current_episode_reward, running_episode_stats
  File "/multiON/habitat_baselines/rl/ppo/ppo_trainer.py", line 1055, in _collect_rollout_step
    outputs = self.envs.step([a[0].item() for a in actions])
  File "/multiON/habitat/core/vector_env.py", line 340, in step
    return self.wait_step()
  File "/multiON/habitat/core/vector_env.py", line 327, in wait_step
    observations.append(read_fn())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 385, in _recv
    raise OSError("got end of file during message")
OSError: got end of file during message
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f61d5742128>>
Traceback (most recent call last):
  File "/multiON/habitat/core/vector_env.py", line 469, in __del__
    self.close()
  File "/multiON/habitat/core/vector_env.py", line 348, in close
    read_fn()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
```

**Comment by erikwijmans** [comment]
That likely means the simulator crashed.  Running `dmesg` immediately after can help figure out why.  If possible, you should also use a new version of habitat-sim.  Object insertion has gotten considerably more robust in the past year.
