### ISSUE TITLE
OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by Raminmoslemi** [facebookresearch/habitat-sim#1162]
Hi
I followed the installation steps for habitat -lab and habitat-sim on 
https://github.com/facebookresearch/habitat-lab
After installation of habitat-lab, I could import habitat in python without any problem. However, after installation of habitat-sim,  when i import habitat i get the following error 

Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import habitat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/acadia13a/data/ramin/habitat-lab/habitat/__init__.py", line 8, in <module>
    from habitat.core.agent import Agent
  File "/net/acadia13a/data/ramin/habitat-lab/habitat/core/agent.py", line 13, in <module>
    from habitat.core.simulator import Observations
  File "/net/acadia13a/data/ramin/habitat-lab/habitat/core/simulator.py", line 17, in <module>
    from habitat.core.dataset import Episode
  File "/net/acadia13a/data/ramin/habitat-lab/habitat/core/dataset.py", line 34, in <module>
    from habitat.core.utils import not_none_validator
  File "/net/acadia13a/data/ramin/habitat-lab/habitat/core/utils.py", line 13, in <module>
    import quaternion  # noqa: F401
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/quaternion/__init__.py", line 28, in <module>
    from .quaternion_time_series import slerp, squad, integrate_angular_velocity, minimal_rotation, angular_velocity
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/quaternion/quaternion_time_series.py", line 8, in <module>
    from quaternion.numba_wrapper import njit
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/quaternion/numba_wrapper.py", line 11, in <module>
    from numba import njit, jit, vectorize, int64, float64, complex128
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/numba/__init__.py", line 14, in <module>
    from numba.core import config
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/home/ma/rmoslemi/anaconda3/envs/slam/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

any idea?

**Comment by Raminmoslemi** [comment]
Problem solved by cloning the stable version of project 
git clone --branch **stable** https://github.com/facebookresearch/habitat-sim.git
