### ISSUE TITLE
Source installaion failure: cmake error

### ISSUE THREAD

**Issue by zhixin-zhao** [facebookresearch/habitat-sim#1716]
## Habitat-Sim version
v0.2.1
I followed the instruction of installation from source in README. And things work fine until execute `python setup.py install`. I have the errors message below.

```bash
~/habitat/habitat-sim-0.2.1$ python setup.py install
running install
running bdist_egg
running egg_info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
CMake Error at cmake/dependencies.cmake:13 (add_subdirectory):
  The source directory

    /home/zhixin/habitat/habitat-sim-0.2.1/src/deps/corrade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:113 (include)


CMake Error at /home/zhixin/miniconda3/envs/habitat/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
  _CORRADE_CONFIGURE_FILE)
Call Stack (most recent call first):
  /home/zhixin/miniconda3/envs/habitat/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCorrade.cmake:311 (find_package_handle_standard_args)
  cmake/dependencies.cmake:15 (find_package)
  CMakeLists.txt:113 (include)


-- Configuring incomplete, errors occurred!
See also "/home/zhixin/habitat/habitat-sim-0.2.1/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 456, in <module>
    include_package_data=True,
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 247, in run
    self.build_extension(ext)
  File "setup.py", line 337, in build_extension
    cwd=self.build_temp,
  File "/home/zhixin/miniconda3/envs/habitat/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zhixin/habitat/habitat-sim-0.2.1/build/lib.linux-x86_64-3.7/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/zhixin/miniconda3/envs/habitat/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=ON', '-DTARGET_HEADLESS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF', '-DBUILD_BASIS_COMPRESSOR=OFF', '/home/zhixin/habitat/habitat-sim-0.2.1/src']' returned non-zero exit status 1.
```

Can someone help with this?

**Comment by erikwijmans** [comment]
This is likely because you don't have the submodules downloaded. Please clone the repo, not download a zip.
