### ISSUE TITLE
ImportError: cannot import name 'LoggingContext' from 'habitat_sim.logging'

### ISSUE THREAD

**Issue by jbga-UA** [facebookresearch/habitat-sim#1735]
## Habitat-Sim version
v0.2.1

## 🐛 Bug

After installing habitat using conda:
```
conda create -n habitat python=3.7 cmake=3.14.0
conda install habitat-sim withbullet -c conda-forge -c aihabitat
```

I am able to execute the c++ viewer but not the python viewer.

```
habitat-viewer --enable-physics --dataset data/replica_cad/replicaCAD.scene_dataset_config.json -- apt_1.scene_instance.json
python examples/viewer.py --dataset data/replica_cad/replicaCAD.scene_dataset_config.json --scene apt_1.scene_instance.json
```

After adding  the habitat-sim dir to my PYTHONPATH I get the following error:

```
Traceback (most recent call last):
  File "examples/viewer.py", line 23, in <module>
    from habitat_sim.logging import LoggingContext, logger
ImportError: cannot import name 'LoggingContext' from 'habitat_sim.logging' (/home/jbga/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/logging.py)
```

## Steps to Reproduce

```
conda create -n habitat python=3.7 cmake=3.14.0
conda activate habitat
conda install habitat-sim withbullet -c conda-forge -c aihabitat
cd habitat-sim
export PYTHONPATH=$(pwd)
python examples/viewer.py --dataset data/replica_cad/replicaCAD.scene_dataset_config.json --scene apt_1.scene_instance.json
```
Error:
```
Traceback (most recent call last):
  File "examples/viewer.py", line 23, in <module>
    from habitat_sim.logging import LoggingContext, logger
ImportError: cannot import name 'LoggingContext' from 'habitat_sim.logging' (/home/jbga/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/logging.py)
```

## Expected behavior

Get a similar behaviour compared to the c++ viewer execution.

## System Info

```
Platform: Linux-5.4.0-109-generic-x86_64-with-debian-buster-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.17
Mac version: 
Python version: 3.7.13
Architecture: 64bit 
Win version:    
System OS: Linux
Release: 5.4.0-109-generic
Version: #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022
Operational System: linux
GCC version: b'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\n'
CMAKE version: b'cmake version 3.14.0\n'
NVIDIA-SMI: b'Wed Apr 27 10:07:04 2022       \n+-----------------------------------------------------------------------------+\n| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |\n|-------------------------------+----------------------+----------------------+\n| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n|                               |                      |               MIG M. |\n|===============================+======================+======================|\n|   0  GeForce GTX 105...  Off  | 00000000:01:00.0  On |                  N/A |\n| N/A   42C    P3    N/A /  N/A |    357MiB /  4040MiB |      2%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n'
Pip packages versions:
b'imageio==2.6.1\nimageio-ffmpeg==0.4.7\nmatplotlib==3.2.2\nnumba==0.55.1\nnumpy==1.21.5\nnumpy-quaternion==2022.4.1\ntqdm==4.64.0\n'
Conda packages versions:
b'attrs                     21.4.0             pyhd8ed1ab_0    conda-forge  19.1.0\ngitpython                 3.1.27             pyhd8ed1ab_0    conda-forge\nimageio                   2.6.1                    py37_0    conda-forge\nimageio-ffmpeg            0.4.7              pyhd8ed1ab_0    conda-forge\nmatplotlib                3.2.2                         1    conda-forge\nnumba                     0.55.1           py37h51133e4_0  \nnumpy                     1.21.5           py37he7a7128_1  \npillow                    6.2.1            py37h6b7be26_0    conda-forge\nscipy                     1.7.3            py37hc147768_0    1.3.0\ntqdm                      4.64.0             pyhd8ed1ab_0    conda-forge\n'
```
- OS: Ubuntu 18.04.6 LTS

**Comment by erikwijmans** [comment]
You'll either need to install the nightly binaries with conda or checkout the `v0.2.1` tag on GitHub (that's the version the binaries in the main channel were built with).
