### ISSUE TITLE
undefined reference to "pow@GLIBC_2.29" &  "log@GLIBC_2.29"

### ISSUE THREAD

**Issue by YHWmz** [facebookresearch/habitat-sim#1810]
I follow the instruction to build habitat-sim with audio flag from source, but got some errors.

## System Info

 - OS : linux Debian 10
 - Python version: Python 3.7.7
 - Glibc: ldd (Debian GLIBC 2.28-10) 2.28

## Steps to Reproduce

1. Clone this github repository.

```
git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
```

2.Install Dependencies
```
pip install -r requirements.txt
sudo apt-get update || true
sudo apt-get install -y --no-install-recommends \
     libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev
```

3.  To use Audio sensors, I enable the audio flag
```
python setup.py install --audio  
```

## Error
```
......
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/SimBindings.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/ShortestPathBindings.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/GltfImporter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum/src/MagnumPlugins/AnyImageImporter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/StbImageImporter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/StbImageConverter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum/src/MagnumPlugins/AnySceneImporter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/BasisImporter/importStaticPlugin.cpp.o
[ 97%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/PrimitiveImporter/importStaticPlugin.cpp.o
[ 98%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/importStaticPlugin.cpp.o
[ 98%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum/src/MagnumPlugins/AnyImageConverter/importStaticPlugin.cpp.o
[ 98%] Building CXX object esp/bindings/CMakeFiles/habitat_sim_bindings.dir/__/__/deps/magnum-plugins/src/MagnumPlugins/StanfordImporter/importStaticPlugin.cpp.o
[100%] Linking CXX executable viewer
[100%] Linking CXX shared module ../../lib.linux-x86_64-3.7/habitat_sim/_ext/habitat_sim_bindings.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: /root/habitat-sim/src/deps/rlr-audio-propagation/RLRAudioPropagationPkg/libs/linux/x64/libRLRAudioPropagation.so: undefined reference to `log@GLIBC_2.29'
/usr/bin/ld: /root/habitat-sim/src/deps/rlr-audio-propagation/RLRAudioPropagationPkg/libs/linux/x64/libRLRAudioPropagation.so: undefined reference to `pow@GLIBC_2.29'
collect2: error: ld returned 1 exit status
make[2]: *** [utils/viewer/CMakeFiles/viewer.dir/build.make:350: utils/viewer/viewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:4732: utils/viewer/CMakeFiles/viewer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target habitat_sim_bindings
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 484, in <module>
    include_package_data=True,
  File "/root/python/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/root/python/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/python/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/python/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/root/python/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/python/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/python/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/python/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/root/python/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/python/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/python/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/root/python/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/python/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 271, in run
    self.build_extension(ext)
  File "setup.py", line 384, in build_extension
    [osp.join(CMAKE_BIN_DIR, "cmake"), "--build", self.build_temp] + build_args
  File "/root/python/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/python/lib/python3.7/site-packages/cmake/data/bin/cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j']' returned non-zero exit status 2.
```

It is strange that my glibc version is 2.28, while the error is " undefined reference to `xxx@GLIBC_2.29'". 

I have no idea how to solve this problem. Please help. Thanks

**Comment by dhruvbatra** [comment]
CC: @sanchitgarg @ChanganVR

**Comment by ChanganVR** [comment]
@YHWmz please refer to this issue for solutions: https://github.com/facebookresearch/rlr-audio-propagation/issues/9

**Comment by YHWmz** [comment]
@ChanganVR Thanks

**Comment by ShunqiM** [comment]
@YHWmz I've encountered the exact same problem as you. I've tried the solutions mentioned in the issue but the problem remains. Would you mind sharing how did you solve this problem?

**Comment by YHWmz** [comment]
@ShunqiM Hi. In my case, the problem is that my cluster only supports GLIBC_2.28. To solve this, I just built GLIBC_2.29 and added libm.so.6 to $LD_LIBRARY_PATH. I hope this may help you

**Comment by ShunqiM** [comment]
@YHWmz Thanks, I'll try again.
