### ISSUE TITLE
Error downloading HM3D_Semantics dataset

### ISSUE THREAD

**Issue by HLinChen** [facebookresearch/habitat-sim#1918]
## Habitat-Sim version
v0.2.2

## Steps to Reproduce

```
python -m habitat_sim.utils.datasets_download --username $API_TOKEN_ID --password $API_TOKEN_SECRET --uids hm3d_full --data-path ./
```
This outputs:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   443  100   443    0     0    850      0 --:--:-- --:--:-- --:--:--   851
100  464M  100  464M    0     0  8703k      0  0:00:54  0:00:54 --:--:-- 10.4M
=======================================================
Dataset (hm3d_minival_glb) successfully downloaded.
Source: '/ssd/hlchen/hm3d/versioned_data/hm3d-0.2/hm3d'
Symlink: '/ssd/hlchen/hm3d/scene_datasets/hm3d'
=======================================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   455  100   455    0     0   1366      0 --:--:-- --:--:-- --:--:--  1366
100   308    0   308    0     0    230      0 --:--:--  0:00:01 --:--:--   607
Traceback (most recent call last):
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/site-packages/habitat_sim/utils/datasets_download.py", line 700, in <module>
    main(sys.argv[1:])
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/site-packages/habitat_sim/utils/datasets_download.py", line 694, in main
    download_and_place(
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/site-packages/habitat_sim/utils/datasets_download.py", line 532, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/data/hlchen/anaconda3/envs/pt/lib/python3.8/tarfile.py", line 1608, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

## Expected behavior

Downloads full HM3D_Semantics data

## System Info

```
ENVIRONMENT INFO:
Platform: Linux-5.4.0-124-generic-x86_64-with-glibc2.17
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.31
Mac version:
Python version: 3.8.13
Architecture: 64bit ELF
Win version:
System OS: Linux
Release: 5.4.0-124-generic
Version: #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022
Operational System: linux
GCC version: b'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0\n'
CMAKE version: b'cmake version 3.16.3\n'

```

**Comment by aclegg3** [comment]
Downloader on `main` is working for v0.2, closing this issue. Please feel free to re-open or open a new issue if problems persist.
