### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by JiayunjieJYJ** [facebookresearch/habitat-sim#2067]
When I install habitat-sim, I run `./build.sh --headless --cmake` in habitat-sim dir, but there is an error:
```
/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/setup.py:362: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  assert StrictVersion(
/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/setup.py:364: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("3.6"), "Must use python3.6 or newer"
running build_ext
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at cmake/dependencies.cmake:13 (add_subdirectory):
  The source directory

    /home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/src/deps/corrade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:71 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
  _CORRADE_CONFIGURE_FILE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCorrade.cmake:311 (find_package_handle_standard_args)
  cmake/dependencies.cmake:15 (find_package)
  CMakeLists.txt:71 (include)


-- Configuring incomplete, errors occurred!
See also "/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/setup.py", line 383, in <module>
    setup(
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/vsis/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/setup.py", line 210, in run
    self.build_extension(ext)
  File "/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/setup.py", line 277, in build_extension
    subprocess.check_call(
  File "/home/vsis/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-H/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/src', '-Bbuild', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/vsis/proj/maans-master/onpolicy/envs/habitat/habitat-sim/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/vsis/anaconda3/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=OFF', '-DTARGET_HEADLESS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.
```
Could you please tell me what should I do?

**Comment by jemo-mh** [comment]
Try `conda install -c aihabitat-nightly habitat-sim` instead use ./build.sh
