### ISSUE TITLE
import habitat_sim error - symbol not found in flat namespace '_RLRA_AddListener'

### ISSUE THREAD

**Issue by Aavu** [facebookresearch/habitat-sim#2126]
## Habitat-Sim version v0.2.2

I am trying to follow the installation instruction from https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md

I have built it successfully on a 2018 Intel Macbook pro. 
I am on the RLRAudioPropagationUpdate branch following the sound-spaces installation instruction.
When I try to import habitat_sim, I get an import error as follows.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<username>/anaconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-macosx-10.9-x86_64.egg/habitat_sim/__init__.py", line 13, in <module>
    import habitat_sim._ext.habitat_sim_bindings
ImportError: dlopen(/Users/<username>/anaconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-macosx-10.9-x86_64.egg/habitat_sim/_ext/habitat_sim_bindings.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_RLRA_AddListener'
```

Any help to fix this would be really appreciated!
I didn't come across any platform specific installation instruction. I am assuming it works on a mac. Please correct me if my understanding is incorrect.
Thanks in advance

**Comment by Aavu** [comment]
Nevermind... found that --audio flag is available only on Linux x64 platforms
