### ISSUE TITLE
Building failed: No rule to make target '/usr/lib/x86_64-linux-gnu/libGLX.so'

### ISSUE THREAD

**Issue by changanc** [facebookresearch/habitat-sim#215]
Hi, I'm currently using Ubuntu 18.04 and gcc 7.4.0. When I ran "python setup.py install", the build would fail because " make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGLX.so', needed by 'deps/magnum-bindings/src/python/_magnum.cpython-37m-x86_64-linux-gnu.so'.  Stop." More detailed output is attached below:

[ 77%] Linking CXX static library libMagnumSceneGraph.a
[ 77%] Built target MagnumSceneGraph
Scanning dependencies of target MagnumDebugTools
Scanning dependencies of target magnum
[ 77%] Building CXX object deps/magnum/src/Magnum/DebugTools/CMakeFiles/MagnumDebugTools.dir/CompareImage.cpp.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGLX.so', needed by 'deps/magnum-bindings/src/python/_magnum.cpython-37m-x86_64-linux-gnu.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.matrixfloat.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.range.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.matrixdouble.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/magnum.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/trade.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/scenegraph.matrix.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.vectorintegral.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/primitives.cpp.o
[ 77%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/scenegraph.cpp.o
[ 78%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/math.vectorfloat.cpp.o
[ 78%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/gl.cpp.o
[ 78%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/shaders.cpp.o
[ 78%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/meshtools.cpp.o
[ 79%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/scenegraph.trs.cpp.o
[ 79%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/platform/glfw.cpp.o
[ 79%] Building CXX object deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/platform/glx.cpp.o
[ 79%] Linking CXX shared module containers.cpython-37m-x86_64-linux-gnu.so
[ 79%] Linking CXX static library libMagnumDebugTools.a
[ 79%] Built target MagnumDebugTools
[ 79%] Built target corrade_containers
[ 79%] Linking CXX static library libTinyGltfImporter.a
[ 79%] Built target TinyGltfImporter
[ 79%] Linking CXX static library libgeo.a
[ 79%] Built target geo
CMakeFiles/Makefile2:4895: recipe for target 'deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/all' failed
make[1]: *** [deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Linking CXX static library libassimp.a
[ 79%] Built target assimp
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 377, in <module>
    zip_safe=False,
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changan/.pyenv/versions/audio_nav/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.build_extension(ext)
  File "setup.py", line 274, in build_extension
    shlex.split("cmake --build {}".format(self.build_temp)) + build_args
  File "/home/changan/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j']' returned non-zero exit status 2.

**Comment by Xiaoming-Zhao** [comment]
@changanc Hi, may I know how you finally solved this issue? Thanks
