### ISSUE TITLE
habitat-sim initialization error,MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by Moon-heart** [facebookresearch/habitat-sim#2215]
## Habitat-Sim version
v0.1.5

## Steps to Reproduce

Traceback (most recent call last):
  File "run.py", line 79, in <module>
    main()
  File "run.py", line 39, in main
    run_exp(**vars(args))
  File "run.py", line 71, in run_exp
    trainer.train()
  File "/home/zzy/robo-vln/robo_vln_baselines/robo_vln_trainer.py", line 858, in train
    self.envs = construct_env(self.config)
  File "/home/zzy/robo-vln/robo_vln_baselines/common/env_utils.py", line 113, in construct_env
    env = VLNCEDaggerEnv(config)
  File "/home/zzy/robo-vln/robo_vln_baselines/common/environments.py", line 12, in __init__
    super().__init__(config.TASK_CONFIG, dataset)
  File "/home/zzy/robo-vln/environments/habitat-lab/habitat/core/env.py", line 333, in __init__
    self._env = Env(config, dataset)
  File "/home/zzy/robo-vln/environments/habitat-lab/habitat/core/env.py", line 104, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/home/zzy/robo-vln/environments/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/zzy/robo-vln/environments/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 185, in __init__
    self._sim = habitat_sim.Simulator(self.sim_config)
  File "<attrs generated init habitat_sim.simulator.Simulator>", line 9, in __init__
  File "/home/zzy/.conda/envs/habitat1/lib/python3.6/site-packages/habitat_sim-0.1.5-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 87, in __attrs_post_init__
    self.__set_from_config(self.config)
  File "/home/zzy/.conda/envs/habitat1/lib/python3.6/site-packages/habitat_sim-0.1.5-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 199, in __set_from_config
    self._config_backend(config)
  File "/home/zzy/.conda/envs/habitat1/lib/python3.6/site-packages/habitat_sim-0.1.5-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 136, in _config_backend
    super().__init__(config.sim_cfg)
MemoryError: std::bad_alloc

The train.log output:

2023-09-27 16:11:52,585 Initializing dataset VLN-CE-v1
2023-09-27 16:11:53,128 Simulator GPU ID [0]
2023-09-27 16:11:53,128 Simulator GPU ID 0
2023-09-27 16:11:53,128 [construct_envs] Using GPU ID 0
2023-09-27 16:11:53,128 Initializing dataset VLN-CE-v1
2023-09-27 16:11:53,675 initializing sim Sim-v0

In addition,I found that habitat-sim can be used normally by using the test scheme provided by the official.

The configuration information is displayed as follows:

 - OS (e.g., Linux):LInux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): python setup.py install --headless --with-cuda
 - Python version:3.6.13
 - GPU models and configuration:NVIDIA RTX A6000
 - CUDA version:12.2
 - PIP/conda dependencies packages versions:21.3.1

**Comment by aclegg3** [comment]
Hey @Moon-heart 

Given that the issue related to an old version of habitat, I don't think this is a problem with the platform which will be investigated or changed.

What are you hoping to get from this issue request? Have you searched for other issues with `MemoryError: std::bad_alloc` which may provide some hints for fixing this on your system?

> In addition,I found that habitat-sim can be used normally by using the test scheme provided by the official.

Are you suggesting that you have a work-around or that some non-training operation is working for you?
