### ISSUE TITLE
Build error using command `python setup.py install --headless --audio` on branch RLRAudioPropagationUpdate

### ISSUE THREAD

**Issue by EntyccE** [facebookresearch/habitat-sim#2240]
I'm installing soundspace 2.0 following the instruction [https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md](url) and I encountered the following error. In brief, cmake cannot found RLRAudioPropagation_LIBRARY variable, which is 
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RLRAudioPropagation_LIBRARY
    linked by target "sensor" in directory D:/Programmes/soundspace/habitat-sim/src/esp/sensor
```
I'm running on a Windows system and my cmake version is the latest. Though the instruction seems to install a version of 3.14.0 but after I run the command of creating the conda environment, it's said that cmake cannot be found. 

The whole output of command `python setup.py install --headless --audio` is 
```
D:\Programmes\soundspace\habitat-sim\setup.py:22: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
running install
running bdist_egg
running egg_info
writing src_python\habitat_sim.egg-info\PKG-INFO
writing dependency_links to src_python\habitat_sim.egg-info\dependency_links.txt
writing requirements to src_python\habitat_sim.egg-info\requires.txt
writing top-level names to src_python\habitat_sim.egg-info\top_level.txt
reading manifest file 'src_python\habitat_sim.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src_python\habitat_sim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Using relative rpath
CMake Deprecation Warning at deps/corrade/CMakeLists.txt:31 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at deps/assimp/CMakeLists.txt:39 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Shared libraries disabled
-- Looking for DirectX...
-- DirectX_PREFIX_PATH changed.
-- Could not locate DirectX
-- Looking for ZLIB...
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;D:/anaconda3/Library/lib/z.lib;debug;D:/anaconda3/Library/lib/z.lib
-- Build an import-only version of Assimp.
CMake Deprecation Warning at deps/assimp/code/CMakeLists.txt:46 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at C:/Users/whao_e/AppData/Local/Programs/Python/Python310/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (rt) does
  not match the name of the calling package (RT).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  deps/assimp/cmake-modules/FindRT.cmake:19 (find_package_handle_standard_args)
  deps/assimp/code/CMakeLists.txt:1013 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find rt (missing: RT_LIBRARY)
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD STEP
-- Disabled importer formats:
-- Enabled exporter formats:
-- Disabled exporter formats: 3DS ASSBIN ASSXML COLLADA OBJ OPENGEX PLY FBX STL X X3D GLTF 3MF ASSJSON STEP
CMake Warning (dev) at cmake/dependencies.cmake:129 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:147 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: C:/Users/whao_e/AppData/Local/Programs/Python/Python310/python.exe (found suitable version "3.10.1", minimum required is "3.7")
-- Bindings being generated for python at C:/Users/whao_e/AppData/Local/Programs/Python/Python310/python.exe
CMake Deprecation Warning at deps/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.10.0
CMake Warning (dev) at deps/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  deps/pybind11/tools/pybind11Tools.cmake:50 (find_package)
  deps/pybind11/tools/pybind11Common.cmake:180 (include)
  deps/pybind11/CMakeLists.txt:200 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: C:/Users/whao_e/AppData/Local/Programs/Python/Python310/python.exe (found suitable version "3.10.1", minimum required is "3.6")
-- OpenEXR is configuring as a cmake subproject
-- Imath was not found, installing from https://github.com/AcademySoftwareFoundation/Imath.git (v3.0.5)
-- Imath is configuring as a cmake sub project
-- Configure Imath 3.0.5, library API version: 28.0.2
-- pkg-config generation disabled
-- -- pkg-config generation disabled
-- Configure OpenEXR 3.0.5, library API version: 29.0.0
CMake Deprecation Warning at deps/magnum/CMakeLists.txt:26 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility Main TestSuite
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
CMake Deprecation Warning at deps/magnum-plugins/CMakeLists.txt:26 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility    
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade AnyImageImporter     
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade 
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade AnyImageImporter     
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade 
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: MeshTools Trade GL Primitives
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade GL MeshTools
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade 
CMake Deprecation Warning at deps/magnum-integration/CMakeLists.txt:29 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility 
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL Shaders 
CMake Deprecation Warning at deps/magnum-bindings/CMakeLists.txt:26 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src   
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL SceneGraph 
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
-- Warning: this does not have an effect - use NO_SYSTEM_FROM_IMPORTED if using imported targets
-- Could NOT find GLFW (missing: GLFW_LIBRARY GLFW_INCLUDE_DIR) 
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR) 
-- Could NOT find Magnum (missing: GlfwApplication Sdl2Application)
    Reason given by package: GlfwApplication is not built by default. Make sure you enabled MAGNUM_WITH_GLFWAPPLICATION when building Magnum. Sdl2Application is not built by default. Make sure you enabled MAGNUM_WITH_SDL2APPLICATION when building Magnum.

-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility    
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL WindowlessWglApplication

-- Warning: this does not have an effect - use NO_SYSTEM_FROM_IMPORTED if using imported targets
Building with ptex support
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src   
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade GL MeshTools Primitives SceneGraph Shaders AnyImageImporter AnySceneImporter DebugTools AnyImageConverter
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade AnyImageImporter 
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility 
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL WindowlessWglApplication

-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL Shaders Trade
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility    
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: GL WindowlessWglApplication

-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility PluginManager
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade GL MeshTools AnyImageImporter AnySceneImporter SceneGraph SceneTools Shaders Primitives
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade MeshTools GL AnyImageImporter Primitives
-- Found MagnumPlugins: D:/Programmes/soundspace/habitat-sim/src/deps/magnum-plugins/src  found components: BasisImporter GltfImporter PrimitiveImporter StanfordImporter StbImageImporter StbImageConverter
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade AnyImageImporter     
-- Found MagnumPlugins: D:/Programmes/soundspace/habitat-sim/src/deps/magnum-plugins/src  found components: AssimpImporter
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: MeshTools Trade GL Primitives
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src  found components: Trade AnyImageImporter 
-- Found MagnumPlugins: D:/Programmes/soundspace/habitat-sim/src/deps/magnum-plugins/src  found components: GltfImporter StbImageImporter StbImageConverter
Building Python bindings
-- Found Corrade: D:/Programmes/soundspace/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility    
-- Found Magnum: D:/Programmes/soundspace/habitat-sim/src/deps/magnum/src   
-- Configuring done (7.3s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RLRAudioPropagation_LIBRARY
    linked by target "sensor" in directory D:/Programmes/soundspace/habitat-sim/src/esp/sensor

-- Generating done (0.9s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "D:\Programmes\soundspace\habitat-sim\setup.py", line 468, in <module>
    setup(
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands       
    self.run_command(cmd)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "D:\Programmes\soundspace\habitat-sim\setup.py", line 271, in run
    self.build_extension(ext)
  File "D:\Programmes\soundspace\habitat-sim\setup.py", line 372, in build_extension
    subprocess.check_call(
  File "C:\Users\whao_e\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\whao_e\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\cmake\\data\\bin\\cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Programmes\\soundspace\\habitat-sim\\build\\lib.win-amd64-3.10\\habitat_sim\\_ext', '-DPYTHON_EXECUTABLE=C:\\Users\\whao_e\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DREL_BUILD_RPATH=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF', '-DBUILD_BASIS_COMPRESSOR=OFF', '-DBUILD_WITH_AUDIO=ON', 'D:\\Programmes\\soundspace\\habitat-sim\\src']' returned non-zero exit status 1.
```

**Comment by EntyccE** [comment]
Oh it seem that Windows is not suitable to build that. Linux is fine.

**Comment by EntyccE** [comment]
I tried on a linux one and it also generate this error. can someone help to diagnose where is the reason?

**Comment by Shelton-wong** [comment]
> I tried on a linux one and it also generate this error. can someone help to diagnose where is the reason?

I also encounter this error，have you solved this？could you tell me how solve this？
