### ISSUE TITLE
Unable to build Datatool due to errors in AudioSensor.cpp 

### ISSUE THREAD

**Issue by YYDreamzure** [facebookresearch/habitat-sim#2257]
## Habitat-Sim version
v0.3.0

I would like to build datatool for generating semantic.ply files for Gibson dataset. However, I am experiencing issues with building the datatool.

I was following the steps from [#648](https://github.com/facebookresearch/habitat-sim/issues/648) and the following errors was incurred:

[ 70%] Building CXX object esp/sensor/CMakeFiles/sensor.dir/AudioSensor.cpp.o
/home/dto/soundspace/habitat-sim/src/esp/sensor/AudioSensor.cpp: In member function ‘virtual bool esp::sensor::AudioSensor::displayObservation(esp::sim::Simulator&)’:
/home/dto/soundspace/habitat-sim/src/esp/sensor/AudioSensor.cpp:312:18: error: ‘logHeader_’ was not declared in this scope
  312 |   ESP_ERROR() << logHeader_ << "Display observation for audio sensor is not used. This function should be unreachable";
      |                  ^~~~~~~~~~
gmake[2]: *** [esp/sensor/CMakeFiles/sensor.dir/build.make:154: esp/sensor/CMakeFiles/sensor.dir/AudioSensor.cpp.o] Error 1
gmake[2]: Leaving directory '/home/dto/soundspace/habitat-sim/build'
gmake[1]: *** [CMakeFiles/Makefile2:5836: esp/sensor/CMakeFiles/sensor.dir/all] Error 2
gmake[1]: Leaving directory '/home/dto/soundspace/habitat-sim/build'
gmake: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "/home/dto/soundspace/habitat-sim/setup.py", line 468, in <module>
    setup(
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dto/soundspace/habitat-sim/setup.py", line 271, in run
    self.build_extension(ext)
  File "/home/dto/soundspace/habitat-sim/setup.py", line 383, in build_extension
    subprocess.check_call(
  File "/home/dto/anaconda3/envs/allure/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j']' returned non-zero exit status 2.

Apparently the problem lies with AudioSensor.cpp logHeader assignment. However, I am unable to rectify the issue.

**Comment by 0mdc** [comment]
@aclegg3 Thoughts?
