### ISSUE TITLE
Build from Source Issue

### ISSUE THREAD

**Issue by Sumireko-Usami** [facebookresearch/habitat-sim#2270]
I was trying to build from source, so I ran python setup.py install in habitat-sim dir, but errors occured. 

check.warn(importable)
creating build\lib.win-amd64-cpython-39\habitat_sim\sensors\noise_models\data
copying habitat_sim\sensors\noise_models\data\redwood-depth-dist-model.npy -> build\lib.win-amd64-cpython-39\habitat_sim\sensors\noise_models\data
running build_ext
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/dependencies.cmake:13 (add_subdirectory):
  The source directory

    D:/habitat-sim/src/deps/corrade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)

CMake Error at D:/anaconda3/envs/pytorch/Library/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
  _CORRADE_CONFIGURE_FILE)
Call Stack (most recent call first):
  D:/anaconda3/envs/pytorch/Library/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCorrade.cmake:311 (find_package_handle_standard_args)
  cmake/dependencies.cmake:15 (find_package)
  CMakeLists.txt:66 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "D:\habitat-sim\setup.py", line 374, in <module>
    setup(
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\habitat-sim\setup.py", line 204, in run
    self.build_extension(ext)
  File "D:\habitat-sim\setup.py", line 268, in build_extension
    subprocess.check_call(
  File "D:\anaconda3\envs\pytorch\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-HD:\\habitat-sim\\src', '-Bbuild\\Release', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\habitat-sim\\build\\lib.win-amd64-cpython-39\\habitat_sim\\_ext', '-DPYTHON_EXECUTABLE=D:\\anaconda3\\envs\\pytorch\\python.exe', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.

What shoud I do? Does this mean I need to install a package named Corrade?

**Comment by jturner65** [comment]
Unfortunately, we do not yett support building from source on Windows.
