### ISSUE TITLE
Replica ImageExtractor .ply file fail to load. 

### ISSUE THREAD

**Issue by MihneaJurca** [facebookresearch/habitat-sim#2341]
I would like to extract images, semantic masks and depth information from Replica dataset using ImageExtractor. I am using exactly this  [code](https://aihabitat.org/docs/habitat-sim/image-extractor.html). I am loading the mesh_semantic.ply as the scene_filepath. I get the following error: 
```
[14:16:44:034595]:[Error]:[Assets] ResourceManager.cpp(1003)::loadStageInternal : Reloading asset `/media/mihnea/0C722848722838BA/replica/office_0/habitat/mesh_semantic.ply` with different configuration not currently supported.Asset may not be rendered correctly.
Traceback (most recent call last):
  File "/home/mihnea/mihnea/GGS/data/scripts/replica_extractor.py", line 131, in <module>
    extractor = ImageExtractor(
  File "/home/mihnea/anaconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.3.0-py3.9-linux-x86_64.egg/habitat_sim/utils/data/data_extractor.py", line 122, in __init__
    self.poses = self.pose_extractor.extract_all_poses()
  File "/home/mihnea/anaconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.3.0-py3.9-linux-x86_64.egg/habitat_sim/utils/data/pose_extractor.py", line 63, in extract_all_poses
    return np.array(poses)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (47, 3) + inhomogeneous part
```

I used the same code in a previous project and it worked just fine with the same hardware.

**Comment by MihneaJurca** [comment]
Solved using an old version of habitat such as:  v0.2.1. [ref](https://github.com/facebookresearch/habitat-sim/issues/2205#issue-1900445640)
