### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rj/Desktop/habitat-sim-challenge-2022/build/lib.linux-x86_64-cpython-39/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/rj/miniconda3/envs/co/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DREL_BUILD_RPATH=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=ON', '-DTARGET_HEADLESS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF', '-DBUILD_BASIS_COMPRESSOR=OFF', '/home/rj/Desktop/habitat-sim-challenge-2022/src']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by renmjie** [facebookresearch/habitat-sim#2517]
I have an issue while installing the sim

python:3.9
tag:habitat-sim-challenge-2022

home/rj/Desktop/habitat-sim-challenge-2022/setup.py:447: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  assert StrictVersion(
/home/rj/Desktop/habitat-sim-challenge-2022/setup.py:449: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("3.7"), "Must use python3.7 or newer"
/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing src_python/habitat_sim.egg-info/PKG-INFO
writing dependency_links to src_python/habitat_sim.egg-info/dependency_links.txt
writing requirements to src_python/habitat_sim.egg-info/requires.txt
writing top-level names to src_python/habitat_sim.egg-info/top_level.txt
reading manifest file 'src_python/habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src_python/habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/attributes_managers.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/logging.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/sensor.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/scene.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/gfx.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/geo.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/sim.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/simulator.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/attributes.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/registry.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/physics.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/errors.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
copying src_python/habitat_sim/metadata.py -> build/lib.linux-x86_64-cpython-39/habitat_sim
creating build/lib.linux-x86_64-cpython-39/habitat_sim/agent
copying src_python/habitat_sim/agent/agent.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent
copying src_python/habitat_sim/agent/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent
creating build/lib.linux-x86_64-cpython-39/habitat_sim/nav
copying src_python/habitat_sim/nav/greedy_geodesic_follower.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/nav
copying src_python/habitat_sim/nav/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/nav
creating build/lib.linux-x86_64-cpython-39/habitat_sim/bindings
copying src_python/habitat_sim/bindings/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/bindings
creating build/lib.linux-x86_64-cpython-39/habitat_sim/robots
copying src_python/habitat_sim/robots/robot_interface.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/robots
copying src_python/habitat_sim/robots/fetch_robot.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/robots
copying src_python/habitat_sim/robots/mobile_manipulator.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/robots
copying src_python/habitat_sim/robots/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/robots
creating build/lib.linux-x86_64-cpython-39/habitat_sim/sensors
copying src_python/habitat_sim/sensors/sensor_suite.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors
copying src_python/habitat_sim/sensors/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors
creating build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/gfx_replay_utils.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/compare_profiles.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/viz_utils.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/datasets_download.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/profiling_utils.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/collect_env.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/common.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/manager_utils.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
copying src_python/habitat_sim/utils/validators.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils
creating build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
copying src_python/habitat_sim/agent/controls/object_controls.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
copying src_python/habitat_sim/agent/controls/controls.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
copying src_python/habitat_sim/agent/controls/default_controls.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
copying src_python/habitat_sim/agent/controls/pyrobot_noisy_controls.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
copying src_python/habitat_sim/agent/controls/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/agent/controls
creating build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/no_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/gaussian_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/poisson_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/redwood_depth_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/speckle_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/sensor_noise_model.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
copying src_python/habitat_sim/sensors/noise_models/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models
creating build/lib.linux-x86_64-cpython-39/habitat_sim/utils/data
copying src_python/habitat_sim/utils/data/pose_extractor.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils/data
copying src_python/habitat_sim/utils/data/data_structures.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils/data
copying src_python/habitat_sim/utils/data/data_extractor.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils/data
copying src_python/habitat_sim/utils/data/__init__.py -> build/lib.linux-x86_64-cpython-39/habitat_sim/utils/data
/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'habitat_sim.sensors.noise_models.data' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'habitat_sim.sensors.noise_models.data' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'habitat_sim.sensors.noise_models.data' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'habitat_sim.sensors.noise_models.data' to be distributed and are
        already explicitly excluding 'habitat_sim.sensors.noise_models.data' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
creating build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models/data
copying src_python/habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-cpython-39/habitat_sim/sensors/noise_models/data
running build_ext
fatal: 不是一个 git 仓库（或者任何父目录）：.git
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using relative rpath
CMake Error at cmake/dependencies.cmake:17 (add_subdirectory):
  The source directory

    /home/rj/Desktop/habitat-sim-challenge-2022/src/deps/corrade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:146 (include)

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
  _CORRADE_CONFIGURE_FILE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCorrade.cmake:311 (find_package_handle_standard_args)
  cmake/dependencies.cmake:19 (find_package)
  CMakeLists.txt:146 (include)

-- Configuring incomplete, errors occurred!
See also "/home/rj/Desktop/habitat-sim-challenge-2022/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/rj/Desktop/habitat-sim-challenge-2022/setup.py", line 456, in <module>
    setup(
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/install.py", line 97, in run
    self.do_egg_install()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/rj/miniconda3/envs/co/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/rj/Desktop/habitat-sim-challenge-2022/setup.py", line 262, in run
    self.build_extension(ext)
  File "/home/rj/Desktop/habitat-sim-challenge-2022/setup.py", line 360, in build_extension
    subprocess.check_call(
  File "/home/rj/miniconda3/envs/co/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rj/Desktop/habitat-sim-challenge-2022/build/lib.linux-x86_64-cpython-39/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/rj/miniconda3/envs/co/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DREL_BUILD_RPATH=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DBUILD_GUI_VIEWERS=ON', '-DTARGET_HEADLESS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF', '-DBUILD_BASIS_COMPRESSOR=OFF', '/home/rj/Desktop/habitat-sim-challenge-2022/src']' returned non-zero exit status 1.

**Comment by yihandai** [comment]
try to clone by
```
git clone --recursive https://github.com/facebookresearch/habitat-sim/
```
or you can use the following command if you didn't add `--recursive` when cloning
```
git submodule update --init --recursive
```
