### ISSUE TITLE
A CMake Error while running build_ext

### ISSUE THREAD

**Issue by TimForss** [facebookresearch/habitat-sim#381]
## ❓ Questions and Help
(habitat) E:\habitat-sim>python setup.py install
running install
running bdist_egg
running egg_info
writing habitat_sim.egg-info\PKG-INFO
writing dependency_links to habitat_sim.egg-info\dependency_links.txt
writing requirements to habitat_sim.egg-info\requires.txt
writing top-level names to habitat_sim.egg-info\top_level.txt
reading manifest file 'habitat_sim.egg-info\SOURCES.txt'
writing manifest file 'habitat_sim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\errors.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\geo.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\gfx.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\logging.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\physics.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\registry.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\scene.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\sensor.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\simulator.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\__init__.py -> build\lib.win-amd64-3.6\habitat_sim
creating build\lib.win-amd64-3.6\habitat_sim\agent
copying habitat_sim\agent\agent.py -> build\lib.win-amd64-3.6\habitat_sim\agent
copying habitat_sim\agent\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\agent
creating build\lib.win-amd64-3.6\habitat_sim\bindings
copying habitat_sim\bindings\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\bindings
creating build\lib.win-amd64-3.6\habitat_sim\nav
copying habitat_sim\nav\greedy_geodesic_follower.py -> build\lib.win-amd64-3.6\habitat_sim\nav
copying habitat_sim\nav\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\nav
creating build\lib.win-amd64-3.6\habitat_sim\sensors
copying habitat_sim\sensors\sensor_suite.py -> build\lib.win-amd64-3.6\habitat_sim\sensors
copying habitat_sim\sensors\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\sensors
creating build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\collect_env.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\common.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\utils
creating build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\default_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\object_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\pyrobot_noisy_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
running build_ext
CMake Error: The source directory "E:habitat-simsrc" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "setup.py", line 379, in <module>
    zip_safe=False,
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.build_extension(ext)
  File "setup.py", line 269, in build_extension
    env=env,
  File "C:\Users\cheng\.conda\envs\habitat\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-HE:habitat-simsrc', '-BbuildRelease', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\\habitat-sim\\build\\lib.win-amd64-3.6\\habitat_sim\\_ext', '-DPYTHON_EXECUTABLE=C:\\Users\\cheng\\.conda\\envs\\habitat\\python.exe', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.

(habitat) E:\habitat-sim>python setup.py install
running install
running bdist_egg
running egg_info
writing habitat_sim.egg-info\PKG-INFO
writing dependency_links to habitat_sim.egg-info\dependency_links.txt
writing requirements to habitat_sim.egg-info\requires.txt
writing top-level names to habitat_sim.egg-info\top_level.txt
reading manifest file 'habitat_sim.egg-info\SOURCES.txt'
writing manifest file 'habitat_sim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
CMake Error: The source directory "E:habitat-simsrc" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "setup.py", line 379, in <module>
    zip_safe=False,
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cheng\.conda\envs\habitat\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cheng\.conda\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.build_extension(ext)
  File "setup.py", line 269, in build_extension
    env=env,
  File "C:\Users\cheng\.conda\envs\habitat\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-HE:habitat-simsrc', '-BbuildRelease', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\\habitat-sim\\build\\lib.win-amd64-3.6\\habitat_sim\\_ext', '-DPYTHON_EXECUTABLE=C:\\Users\\cheng\\.conda\\envs\\habitat\\python.exe', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.

same question occurs on another laptop whose system(win10_1909) is newly installed

**Comment by erikwijmans** [comment]
Windows is currently not supported, you can see the following as a place to start: https://github.com/facebookresearch/habitat-sim/pull/84
