### ISSUE TITLE
Error in building habitat-sim

### ISSUE THREAD

**Issue by shivanshpatel35** [facebookresearch/habitat-sim#455]
Hi, 
I am having trouble building habitat-sim on a headless server. I get the following error on running `python setup.py build_ext --parallel 1 install --headless`
```
running build_ext
-- Shared libraries disabled
-- Looking for ZLIB...
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libz.so;debug;/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libz.so
-- Checking for module 'minizip'
--   No package 'minizip' found
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled formats:
-- Found PythonInterp: /localscratch/shivp.35251576.0/env/bin/python (found suitable version "3.6.3", minimum required is "3.6") 
-- Bindings being generated for python at /localscratch/shivp.35251576.0/env/bin/python
-- Found PythonInterp: /localscratch/shivp.35251576.0/env/bin/python (found version "3.6.3") 
-- pybind11 v2.3.0
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility Main TestSuite 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility PluginManager 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility PluginManager 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade AnyImageImporter 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade AnyImageImporter 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src   
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  GL SceneGraph 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility PluginManager 
-- Could NOT find GLFW (missing: GLFW_LIBRARY GLFW_INCLUDE_DIR) 
-- Could NOT find Magnum (missing: GlfwApplication Sdl2Application WindowlessGlxApplication WindowlessWglApplication) 
Building with ptex support
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility PluginManager 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade GL AnyImageImporter AnySceneImporter MeshTools SceneGraph Shaders AnyImageConverter 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade AnyImageImporter 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src   
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  GL WindowlessEglApplication 
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility PluginManager 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade GL AnyImageImporter AnySceneImporter MeshTools SceneGraph Shaders 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src  found components:  Trade AnyImageImporter 
-- Found MagnumPlugins: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum-plugins/src  found components:  AssimpImporter 
-- Found MagnumPlugins: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum-plugins/src  found components:  StbImageImporter StbImageConverter TinyGltfImporter 
Building Python bindings
-- Found Corrade: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src  found components:  Containers rc Utility 
-- Found Magnum: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/build
[1/226] Building CXX object deps/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/PixelStorage.cpp.o
FAILED: deps/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/PixelStorage.cpp.o 
ccache /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-5.4.0/bin/c++   -I/home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps -I/home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src -Ideps/magnum/src -I/home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/corrade/src -Ideps/corrade/src -isystem /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/cmake/../deps/eigen-git-mirror -isystem /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/cmake/../deps/Sophus -isystem /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/cmake/../deps/rapidjson/include -DVERSION_INFO=\"0.1.3\" -fvisibility=hidden -O2 -g -DNDEBUG -fPIC   -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -pedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wzero-as-null-pointer-constant -Wdouble-promotion -fno-strict-aliasing -std=gnu++14 -MD -MT deps/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/PixelStorage.cpp.o -MF deps/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/PixelStorage.cpp.o.d -o deps/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/PixelStorage.cpp.o -c /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.cpp
In file included from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/move.h:54:0,
                 from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/stl_pair.h:59,
                 from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/utility:70,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.h:33,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.cpp:26:
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:458:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:459:65: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) _GLIBCXX_NOEXCEPT_QUAL>
                                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:462:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:463:67: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) & _GLIBCXX_NOEXCEPT_QUAL>
                                                                   ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:466:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:467:68: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) && _GLIBCXX_NOEXCEPT_QUAL>
                                                                    ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:470:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:471:68: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) _GLIBCXX_NOEXCEPT_QUAL>
                                                                    ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:474:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:475:70: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) & _GLIBCXX_NOEXCEPT_QUAL>
                                                                      ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:478:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:479:71: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) && _GLIBCXX_NOEXCEPT_QUAL>
                                                                       ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:482:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:483:71: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const _GLIBCXX_NOEXCEPT_QUAL>
                                                                       ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:486:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:487:73: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const & _GLIBCXX_NOEXCEPT_QUAL>
                                                                         ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:490:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:491:74: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const && _GLIBCXX_NOEXCEPT_QUAL>
                                                                          ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:494:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:495:74: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const _GLIBCXX_NOEXCEPT_QUAL>
                                                                          ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:498:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:499:76: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const & _GLIBCXX_NOEXCEPT_QUAL>
                                                                            ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:502:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:503:77: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const && _GLIBCXX_NOEXCEPT_QUAL>
                                                                             ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:506:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:507:74: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) volatile _GLIBCXX_NOEXCEPT_QUAL>
                                                                          ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:510:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:511:76: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) volatile & _GLIBCXX_NOEXCEPT_QUAL>
                                                                            ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:514:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:515:77: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) volatile && _GLIBCXX_NOEXCEPT_QUAL>
                                                                             ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:518:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:519:77: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) volatile _GLIBCXX_NOEXCEPT_QUAL>
                                                                             ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:522:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:523:79: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) volatile & _GLIBCXX_NOEXCEPT_QUAL>
                                                                               ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:526:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:527:80: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) volatile && _GLIBCXX_NOEXCEPT_QUAL>
                                                                                ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:530:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:531:80: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const volatile _GLIBCXX_NOEXCEPT_QUAL>
                                                                                ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:534:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:535:82: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const volatile & _GLIBCXX_NOEXCEPT_QUAL>
                                                                                  ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:538:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:539:83: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes...) const volatile && _GLIBCXX_NOEXCEPT_QUAL>
                                                                                   ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:542:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:543:83: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const volatile _GLIBCXX_NOEXCEPT_QUAL>
                                                                                   ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:546:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:547:85: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const volatile & _GLIBCXX_NOEXCEPT_QUAL>
                                                                                     ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:550:49: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _ArgTypes _GLIBCXX_NOEXCEPT_PARM>
                                                 ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:551:86: error: template argument 1 is invalid
     struct is_function<_Res(_ArgTypes......) const volatile && _GLIBCXX_NOEXCEPT_QUAL>
                                                                                      ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:641:45: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _Args _GLIBCXX_NOEXCEPT_PARM>
                                             ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:642:68: error: template argument 1 is invalid
     struct __is_referenceable<_Res(_Args...) _GLIBCXX_NOEXCEPT_QUAL>
                                                                    ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:646:45: error: expected ‘>’ before ‘_GLIBCXX_NOEXCEPT_PARM’
   template<typename _Res, typename... _Args _GLIBCXX_NOEXCEPT_PARM>
                                             ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:647:71: error: template argument 1 is invalid
     struct __is_referenceable<_Res(_Args......) _GLIBCXX_NOEXCEPT_QUAL>
                                                                       ^
In file included from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/move.h:54:0,
                 from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/stl_pair.h:59,
                 from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/utility:70,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.h:33,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.cpp:26:
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:2656:5: error: ‘_GLIBCXX17_INLINE’ does not name a type
     _GLIBCXX17_INLINE constexpr bool is_swappable_v =
     ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:2661:5: error: ‘_GLIBCXX17_INLINE’ does not name a type
     _GLIBCXX17_INLINE constexpr bool is_nothrow_swappable_v =
     ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:2740:5: error: ‘_GLIBCXX17_INLINE’ does not name a type
     _GLIBCXX17_INLINE constexpr bool is_swappable_with_v =
     ^
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/type_traits:2745:5: error: ‘_GLIBCXX17_INLINE’ does not name a type
     _GLIBCXX17_INLINE constexpr bool is_nothrow_swappable_with_v =
     ^
In file included from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/stl_pair.h:59:0,
                 from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/utility:70,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.h:33,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.cpp:26:
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/move.h:136:12: error: ‘_GLIBCXX17_CONSTEXPR’ does not name a type
     inline _GLIBCXX17_CONSTEXPR _Tp*
            ^
In file included from /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/utility:70:0,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.h:33,
                 from /home/shivp/projects/def-msavva/shivp/aihabitat/habitat-sim/src/deps/magnum/src/Magnum/PixelStorage.cpp:26:
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/include/c++/7.3.0/bits/stl_pair.h:79:3: error: ‘_GLIBCXX17_INLINE’ does not name a type
   _GLIBCXX17_INLINE constexpr piecewise_construct_t piecewise_construct =
   ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 379, in <module>
    zip_safe=False,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.build_extension(ext)
  File "setup.py", line 276, in build_extension
    shlex.split("cmake --build {}".format(self.build_temp)) + build_args
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j1']' returned non-zero exit status 1.
```
Thank you very much.

**Comment by dhruvbatra** [comment]
> -- Checking for module 'zzip-zlib-config'
> --   No package 'zzip-zlib-config' found
> -- Checking for module 'minizip'
> --   No package 'minizip' found
> -- Could NOT find GLFW (missing: GLFW_LIBRARY GLFW_INCLUDE_DIR) 

From our readme: 
> See this configuration for a full list of dependencies that our CI installs on a clean Ubuntu VM. If you run into build errors later, this is a good place to check if all dependencies are installed.

**Comment by msavva** [comment]
@shivanshpatel35 the above looks like a compiler error.  Check the gcc version -- the build has been tested with gcc 7+ .

**Comment by shivanshpatel35** [comment]
It seems like some dependencies were not installed. The problem is solved now. Thanks for the help.

**Comment by M-Pixel** [comment]
Which dependencies?
