### ISSUE TITLE
Undefined reference to assimp when building in Ubuntu 20.04

### ISSUE THREAD

**Issue by sotpapathe** [facebookresearch/habitat-sim#658]
## 🐛 Bug

Compiling on Ubuntu 20.04 results in a linker error about assimp, although the
`libassimp-dev` package is installed (error log below).

## Command
`python setup.py install` while in the correct conda environment.

## To Reproduce

Just followed the README instructions, creating a conda environment, installing
dependencies and compiling.

Output from running `python setup.py install` for the 3rd time to hide any successful compilation steps

```
running install
running bdist_egg
running egg_info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
[  1%] Built target CorradePluginManagerObjects
[  3%] Built target CorradeUtilityObjects
[  4%] Built target glog
[  5%] Built target IrrXML
[  5%] Built target corrade-rc
[  7%] Built target Detour
[  8%] Built target Recast
[  9%] Built target glfw
[  9%] Built target MagnumFlextGLObjects
[ 10%] Built target MagnumMathObjects
[ 10%] Built target MagnumGlxContextObjects
[ 10%] Built target MagnumPlatformObjects
[ 11%] Built target MagnumObjects
[ 12%] Built target MagnumTradeObjects
[ 13%] Built target MagnumDebugToolsObjects
[ 13%] Built target AnyImageImporter-dependencies
[ 13%] Built target MagnumSceneGraphObjects
[ 13%] Built target MagnumShaders_RCS-dependencies
[ 13%] Built target MagnumMeshToolsObjects
[ 13%] Built target AnyImageConverter-dependencies
[ 13%] Built target AnySceneImporter-dependencies
[ 13%] Built target AssimpImporter-dependencies
[ 13%] Built target StanfordImporter-dependencies
[ 13%] Built target StbImageConverter-dependencies
[ 13%] Built target BasisImporter-dependencies
[ 13%] Built target PrimitiveImporter-dependencies
[ 13%] Built target StbImageImporter-dependencies
[ 13%] Built target TinyGltfImporter-dependencies
[ 17%] Built target MagnumGLObjects
[ 17%] Built target MagnumImGuiIntegrationShaders_RCS-dependencies
[ 17%] Built target ShaderResources-dependencies
[ 18%] Built target CorradeUtility
[ 19%] Built target simple
[ 19%] Built target particles
[ 19%] Built target offscreen
[ 19%] Built target heightmap
[ 20%] Built target boing
[ 20%] Built target wave
[ 21%] Built target sharing
[ 21%] Built target gears
[ 21%] Built target gamma
[ 21%] Built target splitview
[ 22%] Built target tearing
[ 22%] Built target icon
[ 23%] Built target reopen
[ 23%] Built target events
[ 23%] Built target empty
[ 23%] Built target msaa
[ 25%] Built target threads
[ 25%] Built target cursor
[ 25%] Built target iconify
[ 25%] Built target inputlag
[ 26%] Built target opacity
[ 27%] Built target windows
[ 28%] Built target glfwinfo
[ 28%] Built target joysticks
[ 29%] Built target monitors
[ 29%] Built target timeout
[ 29%] Built target clipboard
[ 29%] Built target triangle-vulkan
[ 30%] Built target title
[ 32%] Built target MagnumShadersObjects
[ 32%] Built target corrade
[ 32%] Built target CorradePluginManager
[ 32%] Built target corrade_containers
[ 32%] Built target CorradeTestSuite
[ 33%] Built target Magnum
[ 33%] Built target MagnumSceneGraph
[ 33%] Built target corrade_pluginmanager
[ 34%] Built target MagnumTrade
[ 36%] Built target MagnumGL
[ 36%] Built target core
[ 36%] Built target AnyImageImporter
[ 36%] Built target AnyImageConverter
[ 37%] Built target AnySceneImporter
[ 38%] Built target StbImageConverter
[ 38%] Built target BasisImporter
[ 38%] Built target TinyGltfImporter
[ 38%] Built target MagnumWindowlessGlxApplication
[ 39%] Built target StbImageImporter
[ 40%] Built target MagnumImGuiIntegration
[ 40%] Built target MagnumGlfwApplication
[ 42%] Built target MagnumMeshTools
[ 45%] Built target io
[ 45%] Built target MagnumPrimitives
[ 46%] Built target MagnumShaders
[ 47%] Built target StanfordImporter
[ 47%] Built target MagnumDebugTools
[ 48%] Built target PrimitiveImporter
[ 75%] Built target assimp
[ 75%] Built target AssimpImporter
[ 77%] Built target magnum
[ 79%] Built target sensor
[ 81%] Built target agent
[ 83%] Built target nav
[ 85%] Built target physics
[ 88%] Built target scene
[ 90%] Built target assets
[ 93%] Built target gfx
[ 94%] Built target geo
[ 95%] Built target sim
[ 95%] Linking CXX executable viewer
[ 98%] Built target habitat_sim_bindings
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(ASELoader.cpp.o): in function `Assimp::ASEImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/ASE/ASELoader.cpp:261: undefined reference to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)'
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(BVHLoader.cpp.o): in function `Assimp::BVHLoader::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/BVH/BVHLoader.cpp:144: undefined reference to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)'
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(ColladaLoader.cpp.o): in function `Assimp::ColladaLoader::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/Collada/ColladaLoader.cpp:255: undefined reference to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)'
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(CSMLoader.cpp.o): in function `Assimp::CSMImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/CSM/CSMLoader.cpp:304: undefined reference to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)'
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(LWSLoader.cpp.o): in function `Assimp::LWSImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/LWS/LWSLoader.cpp:931: undefined reference to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)'
/usr/bin/ld: ../../deps/assimp/code/libassimp.a(MD5Loader.cpp.o):/home/srl/Documents/Git/habitat-sim/src/deps/assimp/code/MD5/MD5Loader.cpp:678: more undefined references to `Assimp::SkeletonMeshBuilder::SkeletonMeshBuilder(aiScene*, aiNode*, bool)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [utils/viewer/CMakeFiles/viewer.dir/build.make:293: utils/viewer/viewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:6260: utils/viewer/CMakeFiles/viewer.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 369, in <module>
    setup(
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/srl/.conda/envs/habitat/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    self.build_extension(ext)
  File "setup.py", line 277, in build_extension
    subprocess.check_call(
  File "/home/srl/.conda/envs/habitat/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j']' returned non-zero exit status 2.
```

## Expected behavior

The compilation to be successful.

## Additional context

I had no issues compiling on the same computer on Ubuntu 18.04.

## System Info

Platform: Linux-5.4.0-37-generic-x86_64-with-glibc2.10
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.31
Python version: 3.8.2
Architecture: 64bit ELF
System OS: Linux
Release: 5.4.0-37-generic
Version: #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020
Operational System: linux
GCC version: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMAKE version: cmake version 3.14.0
NVIDIA-SMI: Wed Jun 24 13:19:56 2020
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P1000        Off  | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8    N/A /  N/A |    255MiB /  4032MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
```
Pip packages versions: pip 20.1.1
Conda packages versions: conda 4.8.3

**Comment by erikwijmans** [comment]
Seems plausible that system assimp and our bundled assimp aren't playing nice.  If you recompile with `--cmake-args="-DUSE_SYSTEM_ASSIMP=ON"` does that work?

**Comment by sotpapathe** [comment]
That worked, thanks!

For future reference I ran:
1. `rm -rf build` to remove anything built previously
2. `python setup.py install --cmake-args="-DUSE_SYSTEM_ASSIMP=ON"`
