### ISSUE TITLE
python examples/example.py failed due to import error of habitat-sim

### ISSUE THREAD

**Issue by poyotamu000** [facebookresearch/habitat-sim#872]
## ❓ Questions and Help

I did this command to local install in a conda environment, and the installation was successful.

```
(habitat_env) [akihiro@Akihiro-2] ~/PycharmProjects/habitat-sim   
conda install habitat-sim withbullet -c conda-forge -c aihabitat
```

However, I cannot do "Testing" with the error.
Help me.

```
python examples/example.py --scene /path/to/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
```

```
(habitat_env) [akihiro@Akihiro-2] ~/PycharmProjects/habitat-sim
% python examples/example.py --scene /data/scene_datasets/habitat-test-scenes/skokloster-castle.glb                                     (git)-[master]
Traceback (most recent call last):
  File "examples/example.py", line 10, in <module>
    import demo_runner as dr
  File "/Users/akihiro/PycharmProjects/habitat-sim/examples/demo_runner.py", line 15, in <module>
    from settings import default_sim_settings, make_cfg
  File "/Users/akihiro/PycharmProjects/habitat-sim/examples/settings.py", line 5, in <module>
    import habitat_sim
  File "/Users/akihiro/anaconda3/envs/habitat_env/lib/python3.6/site-packages/habitat_sim/__init__.py", line 14, in <module>
    from habitat_sim.nav import *
  File "/Users/akihiro/anaconda3/envs/habitat_env/lib/python3.6/site-packages/habitat_sim/nav/__init__.py", line 1, in <module>
    from habitat_sim._ext.habitat_sim_bindings import (
ImportError: dlopen(/Users/akihiro/anaconda3/envs/habitat_env/lib/python3.6/site-packages/habitat_sim/_ext/habitat_sim_bindings.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libBulletDynamics.2.88.dylib
  Referenced from: /Users/akihiro/anaconda3/envs/habitat_env/lib/python3.6/site-packages/habitat_sim/_ext/habitat_sim_bindings.cpython-36m-darwin.so
  Reason: image not found
```

The package habitat-sim is installed in this conda environment.

```
(habitat_env) [akihiro@Akihiro-2] ~/PycharmProjects/habitat-sim                                                                                        
% conda list -n habitat_env                                                                                                             (git)-[master] 
# packages in environment at /Users/akihiro/anaconda3/envs/habitat_env:                                                                                
#                                                                                                                                                      
# Name                    Version                   Build  Channel                                                                                     
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge                                                                               
blas                      1.0                         mkl                                                                                              
bullet                    2.89             py36h72eec15_1    conda-forge                                                                               
ca-certificates           2020.6.20            hecda079_0    conda-forge                                                                               
certifi                   2020.6.20        py36h2432673_2    conda-forge                                                                               
cycler                    0.10.0                     py_2    conda-forge                                                                               
freetype                  2.10.3               ha233b18_0    conda-forge                                                                               
gitdb                     4.0.5                      py_0    conda-forge                                                                               
gitpython                 3.1.9                      py_0    conda-forge                                                                               
habitat-sim               0.1.5                    pypi_0    pypi                                                                                      
jpeg                      9d                   h0b31af3_0    conda-forge   
.............
.............
```

**Comment by Skylion007** [comment]
Your habitat-sim version is 0.1.5 (current version is 0.1.6). Please update it and see if that resolves the error. We also have a nightly channel that you can try to keep in sync with the latest changes to the code base. Alternatively, git checkout the version of this repo that corresponds to the version of Habitat-Sim that is installed.
