### ISSUE TITLE
Non-interactive model error: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by alexklwong** [facebookresearch/habitat-sim#92]
Using the interactive mode seems to work fine, but when running the example.py,  I encounter the following error:

python3 examples/example.py --scene /media/DATA1_3TB/alwong/Workspace/datasets/habitat/test-scenes/skokloster-castle.glb

Traceback (most recent call last):
  File "examples/example.py", line 12, in <module>
    import demo_runner as dr
  File "/media/DATA1_3TB/alwong/Workspace/habitat-sim/examples/demo_runner.py", line 16, in <module>
    import habitat_sim
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/__init__.py", line 12, in <module>
    from .nav import *
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/nav/__init__.py", line 1, in <module>
    from .greedy_geodesic_follower import GreedyGeodesicFollower
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/nav/greedy_geodesic_follower.py", line 6, in <module>
    import habitat_sim.agent
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/agent/__init__.py", line 7, in <module>
    from .agent import *
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/agent/agent.py", line 12, in <module>
    import habitat_sim.bindings as hsim
  File "/usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/bindings/__init__.py", line 25, in <module>
    from habitat_sim._ext.habitat_sim_bindings import Simulator as SimulatorBackend
ImportError: /usr/local/lib/python3.6/dist-packages/habitat_sim-0.1.2-py3.6-linux-x86_64.egg/habitat_sim/_ext/habitat_sim_bindings.so: undefined symbol: _Py_ZeroStruct

**Comment by erikwijmans** [comment]
This happens when there is a mismatch between the python version picked up for compilation and the python version you are using to run things.  The recommended way to deal with this is to install in a conda env/virtual env/pyenv.  https://github.com/facebookresearch/habitat-sim/issues/2 also has a hacky way to deal with this.
