### ISSUE TITLE
Build issue: AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

### ISSUE THREAD

**Issue by ToniRV** [facebookresearch/habitat-sim#95]
## Steps to reproduce

  1. Clone repo
  2. Fresh virtualenv: `virtualenv -p python3.6 ./venv && source ./venv/bin/activate`
  3. Install numpy: `pip install numpy`

## Observed Results

  * What happened? Compilation issue in Ubuntu 18.04 and compiler:
```
/usr/lib/ccache/gcc
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```
Log output:
```
Installed /home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/Pillow-6.1.0-py3.6-linux-x86_64.egg
Searching for numpy-quaternion
Reading https://pypi.org/simple/numpy-quaternion/
Downloading https://files.pythonhosted.org/packages/2e/60/5f944c433e3726a340db9cd0ef24bd4ac34c4d3654ca8dc8f9cc0e21ce78/numpy-quaternion-2019.6.26.15.8.24.tar.gz#sha256=5b11f65f3ef6fa0227530d2c587cc0cf57f64a46d5a121e1cf99adc4c2807014
Best match: numpy-quaternion 2019.6.26.15.8.24
Processing numpy-quaternion-2019.6.26.15.8.24.tar.gz
Writing /tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/setup.cfg
Running numpy-quaternion-2019.6.26.15.8.24/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/egg-dist-tmp-5t0ojvyj
The variable 'package_version' was not present in the environment
Traceback (most recent call last):
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/setup.py", line 117, in <module>
    def __init__(self, name, sourcedir=""):
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/setup.py", line 109, in finalize_options
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 325, in <module>
    zip_safe=False,
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/setup.py", line 117, in <module>
    def __init__(self, name, sourcedir=""):
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/home/tonirv/Code/Simulators/habitat-sim/venv/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-cftr53xo/numpy-quaternion-2019.6.26.15.8.24/setup.py", line 109, in finalize_options
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

```

## Expected Results

  * What did you expect to happen? Successful install...
It does work though if I follow the developer install guide.

**Comment by erikwijmans** [comment]
This seems to be a build issue with one of the dependencies, https://github.com/moble/quaternion.  Can you open an issue there?

You can also see if installing it directly via `pip install numpy numpy-quaternion` works.

**Comment by ToniRV** [comment]
Ok, thanks!
