### ISSUE TITLE
Issues on examples/example.py

### ISSUE THREAD

**Issue by hyang23333** [facebookresearch/habitat-sim#960]
## ❓ Questions and Help
Hi guys!

I have installed habitat-sim using conda with the following command:

`conda install habitat-sim -c conda-forge -c aihabita-nightly`.

However when I tried to run the example/example.py:

`python examples/example.py `

I met this error:
sim_cfg.physics_config_file = ./data/default.physics_config.json
Traceback (most recent call last):
  File "examples/example.py", line 70, in <module>
    perf = demo_runner.example()
  File "/home/yh/habitat-sim/examples/demo_runner.py", line 409, in example
    start_state = self.init_common()
  File "/home/yh/habitat-sim/examples/demo_runner.py", line 322, in init_common
    self._cfg = make_cfg(self._sim_settings)
  File "/home/yh/habitat-sim/examples/settings.py", line 65, in make_cfg
    "sensor_subtype": habitat_sim.SensorSubType.PINHOLE,
AttributeError: module 'habitat_sim' has no attribute 'SensorSubType'
Could anymore provide some help?

**Comment by erikwijmans** [comment]
This should get fixed tonight when the new nightly build goes out
