### ISSUE TITLE
error while running example.py

### ISSUE THREAD

**Issue by mmahdavian** [facebookresearch/habitat-sim#972]
Hi. I am trying to run example/example.py and I get following error. I have tried different ways of installing habitat-sim, but it gives me similar error. Do you know what might be the reason?

```
==== Initialized Sensor Spec: =====
Sensor uuid:  color_sensor
Sensor type:  SensorType.COLOR
Sensor position:  [0.  1.5 0. ]
===================================
Test scenes not downloaded locally, downloading and extracting now...
Downloaded and extracted test scenes data.
Renderer: GeForce RTX 2080 Ti/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 440.33.01
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I1212 11:42:03.716976 23693 simulator.py:80] Loaded navmesh data/scene_datasets/habitat-test-scenes/apartment_1.navmesh
start_state.position	 [ 0.93900377 -1.521554   -2.021698  ] start_state.rotation	 quaternion(0.994037985801697, 0, 0.109034419059753, 0)
shortest_path.geodesic_distance inf
action move_forward
Traceback (most recent call last):
  File "examples/example.py", line 58, in <module>
    perf = demo_runner.example()
  File "/home/mohammad/Mohammad_ws/habitat/habitat-sim/examples/demo_runner.py", line 302, in example
    perf = self.do_time_steps()
  File "/home/mohammad/Mohammad_ws/habitat/habitat-sim/examples/demo_runner.py", line 113, in do_time_steps
    self.display_sample(observations)
  File "/home/mohammad/Mohammad_ws/habitat/habitat-sim/examples/demo_runner.py", line 311, in display_sample
    from habitat_sim.utils.common import d3_40_colors_rgb
ModuleNotFoundError: No module named 'habitat_sim.utils.common'; 'habitat_sim.utils' is not a package

```

**Comment by erikwijmans** [comment]
It seems like you installed a more recent version on habitat-sim than what is in your local repo clone (utils has been a package for over a year now).  Please either update the version on your local repo clone or install that version of the simulator.
